#!/usr/bin/env python3
"""
build_submission.py — produces submission.jsonl per challenge-brief.md §7.2:
one line per canonical test pair in dataset/test_pairs.json, each the exact
output of composer.compose() for that (category, merchant, trigger,
customer?) tuple.

This calls the SAME composer.compose() function bot.py's /v1/tick handler
uses — the submission file and the live HTTP bot are guaranteed to agree
because they share one code path, not two parallel implementations.

Usage (from repo root):
    python scripts/build_submission.py
Writes: submission.jsonl (repo root)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import composer  # noqa: E402

DATASET_DIR = ROOT / "dataset"


def load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_dataset():
    categories = {}
    for f in (DATASET_DIR / "categories").glob("*.json"):
        data = load_json(f)
        categories[data["slug"]] = data

    merchants = {}
    for f in (DATASET_DIR / "merchants").glob("*.json"):
        data = load_json(f)
        merchants[data["merchant_id"]] = data

    customers = {}
    for f in (DATASET_DIR / "customers").glob("*.json"):
        data = load_json(f)
        customers[data["customer_id"]] = data

    triggers = {}
    for f in (DATASET_DIR / "triggers").glob("*.json"):
        data = load_json(f)
        triggers[data["id"]] = data

    test_pairs = load_json(DATASET_DIR / "test_pairs.json")["pairs"]
    return categories, merchants, customers, triggers, test_pairs


def main():
    categories, merchants, customers, triggers, test_pairs = load_dataset()
    print(f"Loaded {len(categories)} categories, {len(merchants)} merchants, "
          f"{len(customers)} customers, {len(triggers)} triggers, {len(test_pairs)} test pairs")

    out_path = ROOT / "submission.jsonl"
    written = 0
    skipped = 0

    with open(out_path, "w", encoding="utf-8") as out:
        for pair in test_pairs:
            test_id = pair["test_id"]
            trigger_id = pair["trigger_id"]
            merchant_id = pair["merchant_id"]
            customer_id = pair.get("customer_id")

            trigger = triggers.get(trigger_id)
            merchant = merchants.get(merchant_id)
            if not trigger or not merchant:
                print(f"  [SKIP] {test_id}: missing trigger or merchant")
                skipped += 1
                continue
            category = categories.get(merchant.get("category_slug"))
            if not category:
                print(f"  [SKIP] {test_id}: missing category {merchant.get('category_slug')}")
                skipped += 1
                continue
            customer = customers.get(customer_id) if customer_id else None
            if trigger.get("scope") == "customer" and trigger.get("customer_id") and not customer:
                # Trigger wants a customer we don't have a profile for —
                # skip rather than fabricate (dataset expansion sometimes
                # references a generated id outside the 15 seed customers'
                # detailed profiles; those are still valid customer JSONs
                # generated by generate_dataset.py, so this should rarely
                # fire, but we guard anyway).
                customer = customers.get(trigger.get("customer_id"))

            composed = composer.compose(category, merchant, trigger, customer, recent_bodies=[])

            line = {
                "test_id": test_id,
                "body": composed["body"],
                "cta": composed["cta"],
                "send_as": composed["send_as"],
                "suppression_key": composed["suppression_key"],
                "rationale": composed["rationale"],
            }
            out.write(json.dumps(line, ensure_ascii=False) + "\n")
            written += 1

    print(f"\nWrote {written} lines to {out_path} ({skipped} skipped)")


if __name__ == "__main__":
    main()
